version: '3.7'
services:
  node-app:
    build: .
    ports:
      - '${API_PORT?}:${API_PORT?}'
    volumes:
      - ./:/app:ro
      - /app/node_modules
    env_file:
      - ./.env
  db:
    image: postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - '${POSTGRES_PORT?}:${POSTGRES_PORT?}'
