version: '3.7'
services:
  node-app:
    build: .
    ports:
      - '${API_PORT?}:${API_PORT?}'
    volumes:
      - ./:/app:ro
      - /app/node_modules
    env_file:
      - ./.env
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
    ports:
      - '${DB_PORT?}:${DB_PORT?}'
